data:extend(
{
  {
    type = "item",
    name = "plumbing",
    icon = "__Engineersvsenvironmentalist__/graphics/icons/parts/plumbing.png",
	icon_size = 28,
    flags = {},
    subgroup = "plumbing",
    
    stack_size = 100000
  },
  {
    type = "recipe",
    name = "plumbing|aluminium",
    order = "aluminium",
    enabled=false,
    ingredients = {{type="item", name="aluminium-plate", amount=1}},
    results = {{type="item", name="plumbing", amount=4}}
  },
  {
    type = "recipe",
    name = "plumbing|ceramics",
    order = "ceramics",
    enabled=false,
    ingredients = {{type="item", name="silicon-nitride", amount=1}},
    results = {{type="item", name="plumbing", amount=2}},
  },
  {
    type = "recipe",
    name = "plumbing|cobalt",
    order = "cobalt",
    enabled=false,
    ingredients = {{type="item", name="cobalt-plate", amount=3}},
    results = {{type="item", name="plumbing", amount=2}},
  },
  {
    type = "recipe",
    name = "plumbing|copper",
    order = "copper",
    enabled=true,
    ingredients = {{type="item", name="copper-plate", amount=5}},
    results = {{type="item", name="plumbing", amount=2}},
  },
  {
    type = "recipe",
    name = "plumbing|gold",
    order = "gold",
    enabled=true,
    ingredients = {{type="item", name="gold-plate", amount=20}},
    results = {{type="item", name="plumbing", amount=2}},
  },
  {
    type = "recipe",
    name = "plumbing|iron",
    enabled=true,
    order = "iron",
    ingredients = {{type="item", name="iron-plate", amount=2}},
    results = {{type="item", name="plumbing", amount=2}},
  },
  {
    type = "recipe",
    name = "plumbing|nickel",
    order = "nickel",
    enabled=false,
    ingredients = {{type="item", name="nickel-plate", amount=10}},
    results = {{type="item", name="plumbing", amount=2}},
  },
  {
    type = "recipe",
    name = "plumbing|silver",
    order = "silver",
    enabled=false,
    ingredients = {{type="item", name="silver-plate", amount=20}},
    results = {{type="item", name="plumbing", amount=2}},
  },
  {
    type = "recipe",
    name = "plumbing|steel",
    order = "steel",
    enabled=false,
    ingredients = {{type="item", name="steel-plate", amount=1}},
    results = {{type="item", name="plumbing", amount=2}},
  },
  {
    type = "recipe",
    name = "plumbing|tin",
    order = "tin",
    enabled=false,
    ingredients = {{type="item", name="tin-plate", amount=20}},
    results = {{type="item", name="plumbing", amount=2}},
  },
  {
    type = "recipe",
    name = "plumbing|titanium",
    order = "titanium",
    enabled=false,
    ingredients = {{type="item", name="titanium-plate", amount=1}},
    results = {{type="item", name="plumbing", amount=4}},
  },
  {
    type = "recipe",
    name = "plumbing|tungsten",
    order = "tungsten",
    enabled=false,
    ingredients = {{type="item", name="tungsten-plate", amount=1}},
    results = {{type="item", name="plumbing", amount=4}},
  },
  {
    type = "recipe",
    name = "plumbing|zinc",
    order = "zinc",
    enabled=false,
    ingredients = {{type="item", name="zinc-plate", amount=10}},
    results = {{type="item", name="plumbing", amount=2}},
  },
  {
    type = "recipe",
    name = "plumbing|brass",
    order = "brass",
    enabled=false,
    ingredients = {{type="item", name="brass-alloy", amount=4}},
    results = {{type="item", name="plumbing", amount=2}},
  },
  {
    type = "recipe",
    name = "plumbing|bronze",
    order = "bronze",
    enabled=false,
    ingredients = {{type="item", name="bronze-alloy", amount=3}},
    results = {{type="item", name="plumbing", amount=2}},
  },
  {
    type = "recipe",
    name = "plumbing|cobalt-steel",
    order = "cobalt-steel",
    enabled=false,
    ingredients = {
    {type="item", name="cobalt-steel-alloy", amount=1}
    },
    results = {{type="item", name="plumbing", amount=4}},
  },
  {
    type = "recipe",
    name = "plumbing|invar",
    order = "invar",
    enabled=false,
    ingredients = {
    {type="item", name="invar-alloy", amount=1}
    },
    results = {{type="item", name="plumbing", amount=4}},
  },
  {
    type = "recipe",
    name = "plumbing|nitinol",
    order = "nitinol",
    enabled=false,
    ingredients = {
    {type="item", name="nitinol-alloy", amount=1}
    },
    results = {{type="item", name="plumbing", amount=20}},
  },
  {
    type = "recipe",
    name = "plumbing|copper-tungsten",
    order = "copper-tungsten",
    enabled=false,
    ingredients = {
    {type="item", name="copper-tungsten-alloy", amount=1}
    },
    results = {{type="item", name="plumbing", amount=4}},
  },
  {
    type = "recipe",
    name = "plumbing|tungsten-carbide",
    order = "tungsten-carbide",
    enabled=false,
    ingredients = {{type="item", name="tungsten-carbide", amount=1}},
    results = {{type="item", name="plumbing", amount=20}},
  },
  {
    type = "recipe",
    name = "plumbing|plastic",
    order = "plastic",
    enabled=false,
    ingredients = {{type="item", name="plastic-bar", amount=1}},
    results = {{type="item", name="plumbing", amount=2}},
  },
  {
    type = "recipe",
    name = "plumbing|stone-brick",
    order = "stone-brick",
    enabled=true,
    ingredients = {{type="item", name="stone-brick", amount=5}},
    results = {{type="item", name="plumbing", amount=2}},
  },
    {
    type = "recipe",
    name = "plumbing|lead",
    order = "lead",
    enabled=false,
    ingredients = {{type="item", name="lead-plate", amount=20}},
    results = {{type="item", name="plumbing", amount=2}},
  },
  }
  )