data:extend(
{
  {
    type = "item",
    name = "tin-crushed",
    icon = "__Engineersvsenvironmentalist__/graphics/icons/metalworking/tin-crushed.png",
	icon_size = 28,
    flags = {},
    subgroup = "tin-processing",
    order = "a-1",
    stack_size = 200
  },
  {
    type = "item",
    name = "tin-sifted",
    icon = "__Engineersvsenvironmentalist__/graphics/icons/metalworking/tin-sifted.png",
	icon_size = 28,
    flags = {},
    subgroup = "tin-processing",
    order = "a-2",
    stack_size = 200
  },
  {
    type = "item",
    name = "tin-slag-1",
    icon = "__Engineersvsenvironmentalist__/graphics/icons/metalworking/tin-slag1.png",
	icon_size = 26,
    flags = {},
    subgroup = "tin-processing",
    order = "a-3",
    stack_size = 200
  },
  {
    type = "item",
    name = "tin-slag-2",
    icon = "__Engineersvsenvironmentalist__/graphics/icons/metalworking/tin-slag2.png",
	icon_size = 26,
    flags = {},
    subgroup = "tin-processing",
    order = "a-4",
    stack_size = 200
  },
  {
    type = "item",
    name = "tin-crude",
    icon = "__Engineersvsenvironmentalist__/graphics/icons/metalworking/tin-crude.png",
	icon_size = 28,
    flags = {},
    subgroup = "tin-processing",
    order = "a-5",
    stack_size = 200
  },
  {
    type = "item",
    name = "tin-plate",
    icon = "__Engineersvsenvironmentalist__/graphics/icons/metalworking/tin-plate.png",
	icon_size = 28,
    flags = {},
    subgroup = "tin-processing",
    order = "a-6",
    stack_size = 200
  },
--Recipes--
  {
    type = "recipe",
    name = "tin-crushing",
    icon = "__Engineersvsenvironmentalist__/graphics/icons/metalworking/tin-crushed.png",
	icon_size = 28,
    category = "crusher",
    subgroup = "tin-processing",
    order="a-1",
    energy_required = 1,
    enabled = false,
    ingredients = {{type="item", name="tin-ore", amount=5}},
    results = {{type="item", name="tin-crushed", amount=5},{type="item", name="gravel", amount=3}},
  },
  {
    type = "recipe",
    name = "tin-sifting",
    icon = "__Engineersvsenvironmentalist__/graphics/icons/metalworking/tin-sifted.png",
	icon_size = 28,
    category = "sifter",
    subgroup = "tin-processing",
    order="a-2",
    energy_required = 1,
    enabled = false,
    ingredients = {{type="item", name="tin-crushed", amount=1},{type="fluid", name="water", amount=1}},
    results = 
    {
    {type="item", name="tin-sifted", amount=1},
    {type="item",name="iron-oxide-crushed", probability=0.1, amount_min=1, amount_max=1},
    {type="item",name="gravel", probability=0.1, amount_min=1, amount_max=1},
    },
  },
  {
    type = "recipe",
    name = "tin-roasting",
    icon = "__Engineersvsenvironmentalist__/graphics/icons/metalworking/tin-slag1.png",
	icon_size = 26,
    category = "smelting",
    subgroup = "tin-processing",
    order="a-3",
    energy_required = 3.5,
    enabled = false,
    ingredients = {{type="item", name="tin-sifted", amount=10},{type="item", name="carbon", amount=1},{type="item", name="sand", amount=1},{type="item", name="calcium-oxide", amount=1}},
    results = {{type="item", name="tin-crude", amount=5},{type="item", name="tin-slag-1", amount=5}},
  },
  {
    type = "recipe",
    name = "tin-roasting-1",
    icon = "__Engineersvsenvironmentalist__/graphics/icons/metalworking/tin-slag2.png",
	icon_size = 26,
    category = "smelting",
    subgroup = "tin-processing",
    order="a-4",
    energy_required = 3.5,
    enabled = false,
    ingredients = {{type="item", name="tin-slag-1", amount=10},{type="item", name="carbon", amount=1},{type="item", name="iron-oxide-crushed", amount=1},{type="item", name="calcium-oxide", amount=1}},
    results = {{type="item", name="tin-crude", amount=5},{type="item", name="tin-slag-2", amount=5}},
  },
    {
    type = "recipe",
    name = "tin-roasting-2",
    icon = "__Engineersvsenvironmentalist__/graphics/icons/metalworking/tin-crude.png",
	icon_size = 28,
    category = "smelting",
    subgroup = "tin-processing",
    order="a-5",
    energy_required = 3.5,
    enabled = false,
    ingredients = {{type="item", name="tin-slag-2", amount=2}},
    results = {{type="item", name="tin-crude", amount=1},{type="item", name="metal-waste", amount=1}},
  },
  {
    type = "recipe",
    name = "tin-refining",
    icon = "__Engineersvsenvironmentalist__/graphics/icons/metalworking/tin-plate.png",
	icon_size = 28,
    category = "smelting",
    subgroup = "tin-processing",
    order="a-6",
    energy_required = 1,
    enabled = false,
    ingredients = {{type="item", name="tin-crude", amount=1}},
    results = 
    {
    {type="item", name="tin-plate", amount=1},
    {type="item",name="iron-oxide-crushed", probability=0.25, amount_min=1, amount_max=1},
    {type="item",name="copper-crushed", probability=0.25, amount_min=1, amount_max=1},
    },
  },
}
)